server:
  port: 10300
spring:
  config:
    import:
     - optional:nacos:database.yaml
     - optional:nacos:log.yaml
  application:
    name: wisdom-third-party
  cloud:
    nacos:
      discovery:
        group: DEV
      server-addr: 119.91.193.254:8848
      config:
        group: DEV
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    top.ctong.wisdom.thirdparty: debug